#!/usr/bin/env bash
# Bash script that configures an nginx server to listen on port 80

sudo service start

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
