#!/usr/bin/env bash
#using while loop to display bad luck for the 4th loop iteration
#display good luck for the 8th loop iteration
#display Best School for the other iterations

school="Best School"
number=1

while [ $number -le 10 ]
do
    if [ $number = 4 ]
    then
        echo "bad luck"
    elif [ $number = 8 ]
    then
        echo "good luck"
    else
        echo "$school"
    fi
        (( number++ ))
done
