#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59

m=1
h=0

while [ $h -le 12 ]
do
    echo "Hour: $h"
    m=1 #Reset minutes back to 1 for each hour
    while [ $m -le 59 ]
    do
        echo "$m"
        ((m++))
    done
    ((h++))
done
