#!/usr/bin/env bash
#Bash script that displays:
#the content of the current directory
#In a list format

for file in ./*
do
   if [ -f "$file" ]
   then
       basename "$file" | cut -d '-' -f 2
   fi
done
