#!/usr/bin/env bash
# Installing firewall and configuring Ports: 22 | 443 | 80
sudo apt update
sudo apt install -y ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
